

CREATE USER 'BPDMBS'@'%'  IDENTIFIED BY 'bpdMBS@123'; #远程登录
CREATE DATABASE IF NOT EXISTS BPDMBS DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON BPDMBS.* TO 'BPDMBS'@'%' IDENTIFIED BY 'bpdMBS@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'BSDBAT'@'%'  IDENTIFIED BY 'bsdBAT@123'; #远程登录
CREATE DATABASE IF NOT EXISTS BSDBAT DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON BSDBAT.* TO 'BSDBAT'@'%' IDENTIFIED BY 'bsdBAT@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'BSDBUI'@'%'  IDENTIFIED BY 'bsdBUI@123'; #远程登录
CREATE DATABASE IF NOT EXISTS BSDBUI DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON BSDBUI.* TO 'BSDBUI'@'%' IDENTIFIED BY 'bsdBUI@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CGDAPI'@'%'  IDENTIFIED BY 'cgdAPI@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CGDAPI DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CGDAPI.* TO 'CGDAPI'@'%' IDENTIFIED BY 'cgdAPI@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CGDEGW'@'%'  IDENTIFIED BY 'cgdEGW@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CGDEGW DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CGDEGW.* TO 'CGDEGW'@'%' IDENTIFIED BY 'cgdEGW@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CGDIGW'@'%'  IDENTIFIED BY 'cgdIGW@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CGDIGW DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CGDIGW.* TO 'CGDIGW'@'%' IDENTIFIED BY 'cgdIGW@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CGDOGW'@'%'  IDENTIFIED BY 'cgdOGW@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CGDOGW DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CGDOGW.* TO 'CGDOGW'@'%' IDENTIFIED BY 'cgdOGW@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CSDACM'@'%'  IDENTIFIED BY 'csdACM@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CSDACM DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CSDACM.* TO 'CSDACM'@'%' IDENTIFIED BY 'csdACM@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CSDACT'@'%'  IDENTIFIED BY 'csdACT@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CSDACT DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CSDACT.* TO 'CSDACT'@'%' IDENTIFIED BY 'csdACT@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CSDBAP'@'%'  IDENTIFIED BY 'csdBAP@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CSDBAP DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CSDBAP.* TO 'CSDBAP'@'%' IDENTIFIED BY 'csdBAP@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CSDBPG'@'%'  IDENTIFIED BY 'csdBPG@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CSDBPG DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CSDBPG.* TO 'CSDBPG'@'%' IDENTIFIED BY 'csdBPG@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CSDLNS'@'%'  IDENTIFIED BY 'csdLNS@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CSDLNS DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CSDLNS.* TO 'CSDLNS'@'%' IDENTIFIED BY 'csdLNS@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CSDLON'@'%'  IDENTIFIED BY 'csdLON@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CSDLON DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CSDLON.* TO 'CSDLON'@'%' IDENTIFIED BY 'csdLON@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CSDPRD'@'%'  IDENTIFIED BY 'csdPRD@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CSDPRD DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CSDPRD.* TO 'CSDPRD'@'%' IDENTIFIED BY 'csdPRD@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CSDSAS'@'%'  IDENTIFIED BY 'csdSAS@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CSDSAS DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CSDSAS.* TO 'CSDSAS'@'%' IDENTIFIED BY 'csdSAS@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'CSDURM'@'%'  IDENTIFIED BY 'csdURM@123'; #远程登录
CREATE DATABASE IF NOT EXISTS CSDURM DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON CSDURM.* TO 'CSDURM'@'%' IDENTIFIED BY 'csdURM@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'GSDPCR'@'%'  IDENTIFIED BY 'gsdPCR@123'; #远程登录
CREATE DATABASE IF NOT EXISTS GSDPCR DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON GSDPCR.* TO 'GSDPCR'@'%' IDENTIFIED BY 'gsdPCR@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'GSDPSM'@'%'  IDENTIFIED BY 'gsdPSM@123'; #远程登录
CREATE DATABASE IF NOT EXISTS GSDPSM DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON GSDPSM.* TO 'GSDPSM'@'%' IDENTIFIED BY 'gsdPSM@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'GSDTCR'@'%'  IDENTIFIED BY 'gsdTCR@123'; #远程登录
CREATE DATABASE IF NOT EXISTS GSDTCR DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON GSDTCR.* TO 'GSDTCR'@'%' IDENTIFIED BY 'gsdTCR@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'PAYACM'@'%'  IDENTIFIED BY 'payACM@123'; #远程登录
CREATE DATABASE IF NOT EXISTS PAYACM DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON PAYACM.* TO 'PAYACM'@'%' IDENTIFIED BY 'payACM@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'TSDNTC'@'%'  IDENTIFIED BY 'tsdNTC@123'; #远程登录
CREATE DATABASE IF NOT EXISTS TSDNTC DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON TSDNTC.* TO 'TSDNTC'@'%' IDENTIFIED BY 'tsdNTC@123' WITH GRANT OPTION;
FLUSH PRIVILEGES;


CREATE USER 'LOGADM'@'%'  IDENTIFIED BY 'logADM@123'; #远程登录
GRANT SElECT ON *.* TO 'LOGADM'@'%' IDENTIFIED BY "logADM@123";
FLUSH PRIVILEGES;